include:
  - board: seeeduino_xiao_ble
    shield: babbit36_dongle
  - board: seeeduino_xiao_ble
    shield: babbit36
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: seeeduino_xiao_ble
    shield: settings_reset
